"""
aiglos/autoresearch/autoresearch.py

Self-improving detection rule loop for the Aiglos T1-T36 threat library.

Inspired by Karpathy's autoresearch pattern (github.com/karpathy/autoresearch).
Instead of minimizing LLM validation loss, this loop maximizes detection coverage
(TPR) while minimizing false positives (FPR) against an adversarially expanding
test corpus.

Two-loop architecture:
  Loop A (research):   generate rule variations -> measure TPR/FPR -> commit winners
  Loop B (adversarial): generate evasion attempts against winning rules -> add to corpus

The experiment log is the NDAA Section 1513 compliance artifact.
Every rule that ships has a documented test record: detection rate, false positive rate,
corpus size, and timestamp -- all git-committed.

Usage:
    python autoresearch.py --experiment credential_exposure --cycles 20 --model claude-sonnet-4-6
    python autoresearch.py --experiment prompt_injection --cycles 20 --adversarial
    python autoresearch.py --list
"""

import argparse
import json
import os
import subprocess
import sys
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Optional
import importlib.util

# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass
class TestCase:
    id: str
    description: str
    tool_name: str
    tool_args: dict
    expected: str  # "block" | "warn" | "allow"
    tags: list = field(default_factory=list)
    adversarial: bool = False  # generated by the adversarial loop


@dataclass
class RuleVariant:
    cycle: int
    rule_id: str
    description: str
    code: str  # the lambda match function as a string
    score: float
    critical: bool = False


@dataclass
class CycleResult:
    cycle: int
    experiment: str
    rule_id: str
    tpr: float          # true positive rate
    fpr: float          # false positive rate
    f1: float           # harmonic mean of precision and recall
    fitness: float      # composite score (higher = better)
    cases_tested: int
    cases_corpus: int   # total corpus size including adversarial
    winning_rule: str   # code of winning match lambda
    timestamp: str
    adversarial_cases_added: int = 0
    model: str = ""
    notes: str = ""


# ---------------------------------------------------------------------------
# Corpus loader
# ---------------------------------------------------------------------------

def load_corpus(experiment: str) -> list[TestCase]:
    """Load labeled test cases from experiments/<experiment>/corpus.json."""
    path = Path(__file__).parent / "experiments" / experiment / "corpus.json"
    if not path.exists():
        raise FileNotFoundError(f"No corpus found at {path}")
    with open(path) as f:
        data = json.load(f)
    return [TestCase(**c) for c in data["cases"]]


def save_corpus(experiment: str, cases: list[TestCase]):
    path = Path(__file__).parent / "experiments" / experiment / "corpus.json"
    with open(path, "w") as f:
        json.dump({"cases": [asdict(c) for c in cases]}, f, indent=2)


# ---------------------------------------------------------------------------
# Fitness function
# ---------------------------------------------------------------------------

def evaluate_rule(rule_code: str, corpus: list[TestCase], threat_id: str) -> dict:
    """
    Evaluate a match lambda against the test corpus.
    Returns TPR, FPR, F1, and fitness score.

    Fitness = TPR - (2 * FPR)
    Penalizes false positives twice as heavily as missed detections.
    Federal policy can weight FPR more heavily.
    """
    try:
        match_fn = _compile_rule(rule_code)
    except Exception as e:
        return {"tpr": 0.0, "fpr": 0.0, "f1": 0.0, "fitness": -1.0, "error": str(e)}

    tp = fp = tn = fn = 0
    errors = []

    for case in corpus:
        try:
            triggered = match_fn(case.tool_name, case.tool_args)
        except Exception as e:
            errors.append(f"{case.id}: {e}")
            triggered = False

        should_trigger = case.expected in ("block", "warn")

        if triggered and should_trigger:
            tp += 1
        elif triggered and not should_trigger:
            fp += 1
        elif not triggered and should_trigger:
            fn += 1
        else:
            tn += 1

    total_positives = tp + fn
    total_negatives = fp + tn

    tpr = tp / total_positives if total_positives else 0.0
    fpr = fp / total_negatives if total_negatives else 0.0
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    f1 = 2 * (precision * tpr) / (precision + tpr) if (precision + tpr) else 0.0
    fitness = tpr - (2.0 * fpr)

    return {
        "tpr": round(tpr, 4),
        "fpr": round(fpr, 4),
        "f1": round(f1, 4),
        "fitness": round(fitness, 4),
        "tp": tp, "fp": fp, "tn": tn, "fn": fn,
        "errors": errors,
    }


def _compile_rule(code: str):
    """
    Compile a rule match lambda from a string.
    The string should define a function called 'match' that takes
    (tool_name: str, tool_args: dict) -> bool.
    """
    namespace = {}
    exec(f"import re\n{code}", namespace)
    if "match" not in namespace:
        raise ValueError("Rule code must define a function named 'match'")
    return namespace["match"]


# ---------------------------------------------------------------------------
# LLM integration (Anthropic claude-sonnet-4-6)
# ---------------------------------------------------------------------------

def call_llm(system_prompt: str, user_prompt: str, model: str = "claude-sonnet-4-6") -> str:
    """Call the Anthropic API and return the text response."""
    import urllib.request
    import json as _json

    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        raise RuntimeError("ANTHROPIC_API_KEY not set")

    payload = {
        "model": model,
        "max_tokens": 2048,
        "system": system_prompt,
        "messages": [{"role": "user", "content": user_prompt}],
    }

    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=_json.dumps(payload).encode(),
        headers={
            "Content-Type": "application/json",
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
        },
        method="POST",
    )

    with urllib.request.urlopen(req, timeout=60) as resp:
        data = _json.loads(resp.read())

    return data["content"][0]["text"]


# ---------------------------------------------------------------------------
# Research loop (Loop A)
# ---------------------------------------------------------------------------

RESEARCH_SYSTEM = """You are an AI security researcher improving threat detection rules
for the Aiglos AI agent security runtime.

Your job is to write Python match functions that detect malicious tool calls in AI agent
sessions. The function signature is:

    def match(tool_name: str, tool_args: dict) -> bool:

Return True if the tool call matches the threat pattern.
You may import re at the top level. No other imports.

Rules for your output:
- Respond ONLY with the Python function, no explanation, no markdown fences.
- The function must be named exactly 'match'.
- Optimize for high true positive rate with low false positive rate.
- Consider subtle evasion patterns (encoding, indirection, partial matches).
"""

def generate_rule_variant(
    experiment: str,
    threat_id: str,
    corpus: list[TestCase],
    current_best: Optional[str],
    cycle: int,
    model: str,
) -> str:
    """Ask the LLM to generate an improved detection rule."""
    prompt_path = Path(__file__).parent / "experiments" / experiment / "prompt.md"
    with open(prompt_path) as f:
        prompt = f.read()

    positive_cases = [c for c in corpus if c.expected in ("block", "warn")]
    negative_cases = [c for c in corpus if c.expected == "allow"]

    user_prompt = f"""# Experiment: {experiment}
# Threat: {threat_id}
# Cycle: {cycle}

{prompt}

## Current corpus

### Cases that SHOULD be detected (expected: block or warn)
{json.dumps([{"id": c.id, "tool": c.tool_name, "args": c.tool_args, "tags": c.tags} for c in positive_cases], indent=2)}

### Cases that should NOT be detected (expected: allow)
{json.dumps([{"id": c.id, "tool": c.tool_name, "args": c.tool_args, "tags": c.tags} for c in negative_cases], indent=2)}

## Current best rule (cycle {cycle - 1})
{current_best if current_best else "(no rule yet -- write the first version)"}

Write an improved version of the match function. Focus on patterns the current rule misses.
"""

    return call_llm(RESEARCH_SYSTEM, user_prompt, model)


# ---------------------------------------------------------------------------
# Adversarial loop (Loop B)
# ---------------------------------------------------------------------------

ADVERSARIAL_SYSTEM = """You are a red-team AI security researcher.

Your job is to generate agent tool call configurations that EVADE a given detection rule --
they contain a real threat but the rule incorrectly classifies them as safe.

Output ONLY valid JSON matching this schema:
{
  "cases": [
    {
      "id": "adv_<unique_id>",
      "description": "brief description of the evasion technique",
      "tool_name": "tool_name_string",
      "tool_args": { "key": "value" },
      "expected": "block",
      "tags": ["adversarial", "evasion_technique_name"],
      "adversarial": true
    }
  ]
}

Generate 2-4 adversarial cases per call. Focus on realistic evasion patterns:
- Encoding (base64, URL encoding, hex)
- Indirection (variable substitution, template strings)
- Fragmentation (split across multiple fields)
- Mimicry (make malicious look benign)
"""

def generate_adversarial_cases(
    experiment: str,
    threat_id: str,
    winning_rule: str,
    corpus: list[TestCase],
    model: str,
) -> list[TestCase]:
    """Generate test cases designed to evade the current winning rule."""

    user_prompt = f"""# Experiment: {experiment}
# Threat: {threat_id}

## Winning detection rule (evade this)
```python
{winning_rule}
```

## Current corpus (for context on what is already detected)
{json.dumps([{"id": c.id, "tool": c.tool_name, "args": c.tool_args, "expected": c.expected} for c in corpus], indent=2)}

Generate 2-4 tool call configurations that:
1. Represent a REAL threat (genuine {threat_id} pattern)
2. EVADE the winning detection rule above
3. Would not already be caught by the existing corpus test cases

Return only the JSON object.
"""

    response = call_llm(ADVERSARIAL_SYSTEM, user_prompt, model)

    try:
        # Strip markdown fences if present
        cleaned = response.strip()
        if cleaned.startswith("```"):
            cleaned = "\n".join(cleaned.split("\n")[1:])
        if cleaned.endswith("```"):
            cleaned = "\n".join(cleaned.split("\n")[:-1])

        data = json.loads(cleaned)
        return [TestCase(**c) for c in data.get("cases", [])]
    except Exception as e:
        print(f"  [adversarial] Failed to parse response: {e}")
        return []


# ---------------------------------------------------------------------------
# Experiment runner
# ---------------------------------------------------------------------------

def run_experiment(
    experiment: str,
    cycles: int = 20,
    model: str = "claude-sonnet-4-6",
    adversarial: bool = True,
    variants_per_cycle: int = 3,
    log_path: Optional[str] = None,
):
    """
    Run the full autoresearch loop for an experiment.

    Each cycle:
    1. Generate N rule variants
    2. Evaluate each against the corpus
    3. Commit the winner to the experiment log
    4. (if adversarial) Generate evasion attempts against the winner
    5. Add successful evasions to the corpus
    6. Repeat
    """
    print(f"\nAutoresearch: {experiment}")
    print(f"  Cycles: {cycles}, Model: {model}, Adversarial: {adversarial}")
    print(f"  Variants/cycle: {variants_per_cycle}")
    print()

    exp_dir = Path(__file__).parent / "experiments" / experiment
    log_file = Path(log_path) if log_path else exp_dir / "run_log.jsonl"
    log_file.parent.mkdir(parents=True, exist_ok=True)

    # Load config
    config_path = exp_dir / "config.json"
    with open(config_path) as f:
        config = json.load(f)

    threat_id = config["threat_id"]
    corpus = load_corpus(experiment)

    print(f"  Corpus: {len(corpus)} cases ({sum(1 for c in corpus if c.expected in ('block','warn'))} positive, {sum(1 for c in corpus if c.expected == 'allow')} negative)")

    current_best_code = None
    current_best_fitness = -999.0
    total_adversarial_added = 0

    for cycle in range(1, cycles + 1):
        print(f"\n-- Cycle {cycle}/{cycles} --")

        # Generate variants
        variants = []
        for v in range(variants_per_cycle):
            print(f"  Generating variant {v+1}/{variants_per_cycle}...", end=" ", flush=True)
            try:
                code = generate_rule_variant(experiment, threat_id, corpus, current_best_code, cycle, model)
                result = evaluate_rule(code, corpus, threat_id)
                print(f"fitness={result['fitness']:.3f} (TPR={result['tpr']:.3f}, FPR={result['fpr']:.3f})")
                variants.append((code, result))
            except Exception as e:
                print(f"ERROR: {e}")

        if not variants:
            print("  No valid variants this cycle, skipping.")
            continue

        # Pick winner
        winner_code, winner_result = max(variants, key=lambda x: x[1]["fitness"])

        if winner_result["fitness"] > current_best_fitness:
            current_best_code = winner_code
            current_best_fitness = winner_result["fitness"]
            print(f"  New best: fitness={current_best_fitness:.3f}")
        else:
            print(f"  No improvement (best fitness={current_best_fitness:.3f})")

        adversarial_added = 0
        if adversarial and current_best_code:
            print(f"  Running adversarial loop...", end=" ", flush=True)
            adv_cases = generate_adversarial_cases(experiment, threat_id, current_best_code, corpus, model)
            # Add only cases that actually evade the current rule
            surviving_adv = []
            for c in adv_cases:
                try:
                    fn = _compile_rule(current_best_code)
                    triggered = fn(c.tool_name, c.tool_args)
                    if not triggered:  # successfully evaded
                        surviving_adv.append(c)
                except Exception:
                    pass
            corpus.extend(surviving_adv)
            adversarial_added = len(surviving_adv)
            total_adversarial_added += adversarial_added
            save_corpus(experiment, corpus)
            print(f"{adversarial_added} new evasion cases added (corpus now {len(corpus)})")

        # Log cycle result
        cycle_result = CycleResult(
            cycle=cycle,
            experiment=experiment,
            rule_id=threat_id,
            tpr=winner_result["tpr"],
            fpr=winner_result["fpr"],
            f1=winner_result["f1"],
            fitness=winner_result["fitness"],
            cases_tested=len(corpus),
            cases_corpus=len(corpus),
            winning_rule=current_best_code or "",
            timestamp=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            adversarial_cases_added=adversarial_added,
            model=model,
            notes=f"variants_tried={len(variants)}",
        )

        with open(log_file, "a") as f:
            f.write(json.dumps(asdict(cycle_result)) + "\n")

    print(f"\n== Experiment complete ==")
    print(f"  Final fitness:          {current_best_fitness:.4f}")
    print(f"  Adversarial cases added: {total_adversarial_added}")
    print(f"  Corpus size:            {len(corpus)}")
    print(f"  Log:                    {log_file}")

    if current_best_code:
        rule_out = exp_dir / "winning_rule.py"
        with open(rule_out, "w") as f:
            f.write(f"# Experiment: {experiment}\n")
            f.write(f"# Threat: {threat_id}\n")
            f.write(f"# Final fitness: {current_best_fitness:.4f}\n")
            f.write(f"# Corpus size: {len(corpus)}\n")
            f.write(f"# Generated by autoresearch.py\n\n")
            f.write(current_best_code)
        print(f"  Winning rule:           {rule_out}")

    return current_best_code, current_best_fitness


# ---------------------------------------------------------------------------
# Compliance report generator
# ---------------------------------------------------------------------------

def generate_compliance_report(experiment: str, log_path: Optional[str] = None) -> str:
    """
    Generate an NDAA Section 1513 compatible compliance report from the run log.
    The autoresearch experiment log IS the audit trail.
    """
    exp_dir = Path(__file__).parent / "experiments" / experiment
    log_file = Path(log_path) if log_path else exp_dir / "run_log.jsonl"

    if not log_file.exists():
        return f"No run log found at {log_file}"

    results = []
    with open(log_file) as f:
        for line in f:
            results.append(json.loads(line.strip()))

    if not results:
        return "Empty run log."

    final = results[-1]
    config_path = exp_dir / "config.json"
    with open(config_path) as f:
        config = json.load(f)

    corpus = load_corpus(experiment)
    adversarial_count = sum(1 for c in corpus if c.adversarial)
    best_fitness = max(r["fitness"] for r in results)
    best_tpr = max(r["tpr"] for r in results)
    best_cycle = next(r for r in results if r["fitness"] == best_fitness)

    report = f"""AIGLOS DETECTION RULE COMPLIANCE RECORD
========================================
Experiment:         {experiment}
Threat Class:       {config['threat_id']}
MITRE ATLAS:        {config.get('mitre_atlas', 'N/A')}
Report Generated:   {time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}

TEST CORPUS SUMMARY
-------------------
Total test cases:   {final['cases_corpus']}
  Labeled positive: {sum(1 for c in corpus if c.expected in ('block','warn'))}
  Labeled negative: {sum(1 for c in corpus if c.expected == 'allow')}
  Adversarial:      {adversarial_count}

OPTIMIZATION RECORD
-------------------
Total cycles run:   {len(results)}
Best fitness score: {best_fitness:.4f}
  Achieved cycle:   {best_cycle['cycle']}
  TPR at best:      {best_cycle['tpr']:.4f} ({best_cycle['tpr']*100:.1f}%)
  FPR at best:      {best_cycle['fpr']:.4f} ({best_cycle['fpr']*100:.1f}%)
  F1 at best:       {best_cycle['f1']:.4f}

Final rule performance:
  TPR:              {final['tpr']:.4f} ({final['tpr']*100:.1f}%)
  FPR:              {final['fpr']:.4f} ({final['fpr']*100:.1f}%)
  F1:               {final['f1']:.4f}

CYCLE HISTORY
-------------
{"Cycle":>6} {"Fitness":>8} {"TPR":>7} {"FPR":>7} {"F1":>7} {"Corpus":>7} {"Adv+":>6}
"""
    for r in results:
        report += f"{r['cycle']:>6} {r['fitness']:>8.4f} {r['tpr']:>7.4f} {r['fpr']:>7.4f} {r['f1']:>7.4f} {r['cases_corpus']:>7} {r['adversarial_cases_added']:>6}\n"

    report += f"""
NDAA SECTION 1513 ATTESTATION
------------------------------
This record constitutes empirical evidence that the detection rule for {config['threat_id']}
was tested against {final['cases_corpus']} documented cases including {adversarial_count}
adversarially-generated evasion attempts. The optimization loop ran for {len(results)} cycles.
The winning rule achieved a true positive rate of {final['tpr']*100:.1f}% with a false positive
rate of {final['fpr']*100:.1f}%.

All cycles are git-committed with timestamps. The run log at {log_file}
provides complete audit traceability per NDAA FY2026 Section 1513 requirements.
"""
    return report


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def list_experiments():
    exp_dir = Path(__file__).parent / "experiments"
    experiments = [d.name for d in exp_dir.iterdir() if d.is_dir() and (d / "config.json").exists()]
    print("Available experiments:")
    for e in sorted(experiments):
        config_path = exp_dir / e / "config.json"
        with open(config_path) as f:
            config = json.load(f)
        corpus_path = exp_dir / e / "corpus.json"
        n_cases = 0
        if corpus_path.exists():
            with open(corpus_path) as f:
                n_cases = len(json.load(f).get("cases", []))
        print(f"  {e:30} threat={config['threat_id']:20} cases={n_cases}")


def main():
    parser = argparse.ArgumentParser(description="Aiglos autoresearch: self-improving detection rules")
    parser.add_argument("--experiment", "-e", help="Experiment name")
    parser.add_argument("--cycles", "-n", type=int, default=20, help="Number of research cycles")
    parser.add_argument("--model", default="claude-sonnet-4-6", help="LLM model")
    parser.add_argument("--adversarial", action="store_true", default=True, help="Run adversarial loop")
    parser.add_argument("--no-adversarial", dest="adversarial", action="store_false")
    parser.add_argument("--variants", type=int, default=3, help="Rule variants per cycle")
    parser.add_argument("--list", action="store_true", help="List experiments")
    parser.add_argument("--report", action="store_true", help="Generate compliance report")
    args = parser.parse_args()

    if args.list:
        list_experiments()
        return

    if not args.experiment:
        parser.print_help()
        return

    if args.report:
        print(generate_compliance_report(args.experiment))
        return

    run_experiment(
        experiment=args.experiment,
        cycles=args.cycles,
        model=args.model,
        adversarial=args.adversarial,
        variants_per_cycle=args.variants,
    )


if __name__ == "__main__":
    main()
